language: java

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - horridge@stanford.edu
    on_success: never
    on_failure: always

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

