language: java
git:
  depth: 3
matrix:
  include:
  - jdk: oraclejdk7
    env: DEPLOY=true
  - jdk: openjdk7
  - jdk: oraclejdk8
install: mvn install -DskipTests=true
script: mvn test -Dassembly.skipAssembly=true -B
after_success:
  - test "$DEPLOY" = true -a "$TRAVIS_PULL_REQUEST" = false 
    && mvn source:jar deploy --settings .travis-settings.xml -DskipTests=true -B
env:
  global:
  - secure: iYIASqS+PJ/SBZOsbzjoSQpBsbJCJKsPdDUKgfGuN5fKq5L5IAHW2yqu5l3+3Ky6PYmYoWwofy6Je9swWi+UtviBTwEm0xknN9WJyMSytnNKJ6l+ov6BBzUvfX+4TRsTuXw1Rf55E8dR9RB3bJzY6y3AyZpbCYjluFCQi90S3Op8nzNacpZX8IIowD7UagvshZwY5EhzWS1ct1sCkPfbNK+9frSg7trLi7AiY4AKSgB3n3tA4so8Zol+IgHVbFapi8nGdPGxLEvr5/NenFQ+iJUDS1YYMpfw/5qSpgGanFa3eBWoICI/7vXYk2wDEqa/f5J+dqZIDXYUFyo/BJbrnGUMkLXt96obpslXXZgzU9HmdALrdiwhOzxJiiicLIGLFgT7VJlv2XpdaDqaMbpaEXT+E+zbQZscaL1AvD3KEilEzhgQsciDV971L8vafWeBlu1Kb6xCW/1meu5W8Fze0Mfq6EyUo8lDHhLfeceBaXRPiy4ljh35vO/Xfx36bKhjRp4dOjGavqWGsKiFy3JPdGtRo4i3maPMhL5dgHYsiBhvGG4HCYNsXOefQ97ZDo6kUWyIf6RqKNMzhmnNN1pCb0K3TbIHJ0bBAMngXvp8BVxsWoCnd0RhaIvhF3nzKn9q72JBkdZ27YvfOfH0rkj2U7NHE4oR60A3Zhw7PufjVtM=
  - secure: Qi9LJZSVmIyNLpRBcal5Zfwvm7xrMfatZjxMdUhxBl2GiDgQ/oOTiGVOqhIUBhLzJrTxPzqbuDncrrUgI6G1j7t4RQ2trqcC7uBxnszDAx9UZvMeqbIXezSfj5fb7CD2xshPJRu9udIAyGIYyXTNMsM/ZF/zNA/3IzhmV6xnO8/G3T5SpE8DIIhLSxTimquMH8LpQc8qDpxoWZMdJqO0bN7Q90Ysvo0t9a0vl2PIM9fe5LXr7Zk4iUmgROqHTz+9cJnzWL1jVCEHwKCNJDRTp6owREeJBf5NtHHtil7gwnHeuTYf3W3Qyo0l53+iSvFoV8ipjfvrCkBiC8xvu+9qX1mjSdsFdtvfl0mlBlV4yp56zHOr/xE3uYFrtmuFd8BGUCBpNqJu3z2PfKek1buEVFVpAE7lJGGfGOI9g0PBx7u30PSlO6e/YIPXe5Fm9HD0r7W6Tda1sjkaporquSc7PKzP+iBcBfAnVq5VLtdR2oLKq9SES2Y6eunzSwGkILpnbd21IN0LuSZ8bviSy0117M6hEtbmxHX/AuT+nhLGxOFUsGJX2tg0GgtDINIJ9LQOGy2SZlODEf8jXys7/zKyfajl9shoUdg3jFMbIsNMBvP+WP/UFMOQveB4HJ+acne7/qpJ+i/Wu2kWsG+p70Izqs3FbwnSJ0zPUIafXeUr2Tc=
